In [2]:
#!/usr/bin/env python

"""main.ipynb:Main python notebook to run analysis and models for the bee project.
"""
__author__      = "Vincent Amedekah, Nathan Smooha, Elizabeth Gutierrez-Zaheer "
__copyright__   = "Copyright 2022, Bee Project"

import numpy as np
import matplotlib.pyplot as plt
from numpy import datetime64
import get_data as data

dataset_a, dataset_b,dataset_a_test,dataset_b_test,weather_data, bee_data, bee_full_data, air_data = data.get_data()

In [3]:
dataset_a.head()

,year,state,colonies_inventory,days_with_aqi,good_days,moderate_days,unhealthy_for_sensitive_groups_days,unhealthy_days,very_unhealthy_days,hazardous_days,...,90th_percentile_aqi,median_aqi,days_co,days_no2,days_ozone,days_pm2.5,days_pm10,temperature_max,temperature_min,precipitation_total
1326,1987-01-01,alabama,46000,230.571429,130.714286,66.428571,24.428571,7.857143,1.142857,0.000000,...,107.571429,46.285714,13.428571,0.000000,181.142857,0.0,36.000000,92.6,32.5,48.13
1327,1987-01-01,arizona,80000,162.100000,88.700000,60.500000,11.900000,1.000000,0.000000,0.000000,...,76.400000,42.600000,40.800000,6.100000,79.200000,0.0,36.000000,93.1,27.1,13.28
1328,1987-01-01,arkansas,29000,184.000000,136.333333,35.333333,8.666667,3.666667,0.000000,0.000000,...,64.000000,31.666667,0.000000,16.666667,101.666667,0.0,65.666667,93.5,28.9,53.10
1329,1987-01-01,california,540000,302.163265,168.612245,74.918367,29.591837,17.551020,11.469388,0.020408,...,110.979592,53.102041,30.571429,63.469388,190.734694,0.0,17.387755,89.5,31.4,19.70
1330,1987-01-01,colorado,44000,222.000000,134.388889,74.888889,10.500000,1.777778,0.444444,0.000000,...,70.333333,38.333333,46.388889,25.055556,107.666667,0.0,42.888889,82.6,12.4,18.82

In [4]:
dataset_b.head()

,year,state,colonies_inventory,colonies_renovated_pct,colonies_loss_deadout_pct,colonies_disease_pct,colonies_varroa_mites_pct,colonies_other_causes_pct,colonies_pesticides_pct,colonies_other_pests_pct,...,90th_percentile_aqi,median_aqi,days_co,days_no2,days_ozone,days_pm2.5,days_pm10,temperature_max,temperature_min,precipitation_total
234,2015-01-01,alabama,7000,4.25,15.50,0.050,23.225,4.325,1.825,31.225,...,56.222222,39.333333,0.000000,0.666667,137.666667,145.722222,3.222222,91.9,30.0,61.36
235,2015-01-01,arizona,26000,26.75,19.00,1.775,34.725,9.525,10.225,19.775,...,66.230769,40.461538,0.000000,3.384615,207.615385,45.153846,103.076923,94.2,28.1,14.39
236,2015-01-01,arkansas,24000,10.75,16.00,2.375,47.700,9.675,9.800,29.225,...,54.454545,35.090909,0.000000,2.636364,157.727273,87.909091,0.000000,91.6,26.1,67.31
237,2015-01-01,california,275000,13.00,11.75,7.375,38.200,11.550,15.450,15.450,...,84.537037,49.425926,0.074074,5.592593,213.555556,111.018519,13.962963,91.0,32.8,15.04
238,2015-01-01,colorado,29000,5.00,11.25,7.575,37.825,4.525,9.900,7.150,...,54.774194,35.451613,0.096774,9.354839,202.193548,19.612903,58.709677,81.8,14.2,21.73

In [5]:
dataset_a['state'].unique()

array(['alabama', 'arizona', 'arkansas', 'california', 'colorado',
       'florida', 'georgia', 'hawaii', 'idaho', 'illinois', 'indiana',
       'iowa', 'kansas', 'kentucky', 'louisiana', 'maine', 'michigan',
       'minnesota', 'mississippi', 'missouri', 'montana', 'nebraska',
       'new jersey', 'new york', 'north carolina', 'north dakota', 'ohio',
       'oregon', 'pennsylvania', 'south dakota', 'tennessee', 'texas',
       'utah', 'vermont', 'virginia', 'washington', 'west virginia',
       'wisconsin', 'wyoming'], dtype=object)

In [6]:
dataset_b['state'].unique()

array(['alabama', 'arizona', 'arkansas', 'california', 'colorado',
       'florida', 'georgia', 'hawaii', 'idaho', 'illinois', 'indiana',
       'iowa', 'kansas', 'kentucky', 'louisiana', 'maine', 'michigan',
       'minnesota', 'mississippi', 'missouri', 'montana', 'nebraska',
       'new jersey', 'new york', 'north carolina', 'north dakota', 'ohio',
       'oregon', 'pennsylvania', 'south dakota', 'tennessee', 'texas',
       'utah', 'vermont', 'virginia', 'washington', 'west virginia',
       'wisconsin', 'wyoming'], dtype=object)

In [7]:
dataset_a.describe()

,colonies_inventory,days_with_aqi,good_days,moderate_days,unhealthy_for_sensitive_groups_days,unhealthy_days,very_unhealthy_days,hazardous_days,max_aqi,90th_percentile_aqi,median_aqi,days_co,days_no2,days_ozone,days_pm2.5,days_pm10,temperature_max,temperature_min,precipitation_total
count,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000,1365.000000
mean,68871.062271,268.630393,205.498515,54.069963,6.971611,1.753134,0.309633,0.027538,125.937976,64.191300,35.413527,10.400817,15.771760,146.786255,68.430402,27.241160,86.332835,20.625582,37.348856
std,95224.758461,60.092036,55.800139,26.077624,7.327673,2.944208,1.062747,0.173325,46.872534,17.097697,7.152384,19.841709,22.029114,66.929664,70.245017,31.691355,5.248238,15.901532,14.779546
min,3000.000000,50.263158,43.894737,0.500000,0.000000,0.000000,0.000000,0.000000,42.500000,27.333333,14.250000,0.000000,0.000000,0.000000,0.000000,0.000000,72.800000,-12.200000,6.560000
25%,12000.000000,227.200000,162.583333,35.842105,1.157895,0.068966,0.000000,0.000000,98.300000,52.260870,30.769231,0.000000,1.272727,98.800000,3.117647,3.545455,82.500000,10.100000,25.110000
50%,35000.000000,272.043478,205.500000,52.000000,4.000000,0.434783,0.000000,0.000000,118.153846,60.400000,35.962963,1.000000,5.727273,148.818182,57.675000,15.761905,86.000000,19.000000,38.440000
75%,80000.000000,320.615385,247.761905,71.210526,10.900000,2.142857,0.147059,0.000000,146.083333,74.647059,39.933333,12.685714,23.954545,197.000000,104.225000,37.960000,90.400000,28.600000,47.950000
max,620000.000000,365.333333,361.500000,130.666667,36.910714,19.772727,12.312500,3.608696,622.436364,134.363636,54.096774,153.437500,131.862069,326.000000,326.333333,182.500000,101.600000,85.969144,79.480000

In [8]:
dataset_b.describe()

,colonies_inventory,colonies_renovated_pct,colonies_loss_deadout_pct,colonies_disease_pct,colonies_varroa_mites_pct,colonies_other_causes_pct,colonies_pesticides_pct,colonies_other_pests_pct,colonies_unknown_causes_pct,pct_beekeepers_exclusive_state,...,90th_percentile_aqi,median_aqi,days_co,days_no2,days_ozone,days_pm2.5,days_pm10,temperature_max,temperature_min,precipitation_total
count,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,...,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000
mean,68967.032967,7.261294,11.363553,3.490354,31.415629,6.217277,6.801435,11.888858,4.317582,87.738751,...,54.818950,34.979716,0.170188,5.203739,175.705873,123.012133,13.724926,86.683092,21.073568,39.390526
std,100305.722069,5.217433,4.163648,3.349669,12.027392,3.834975,6.024167,10.755110,3.499764,18.048177,...,8.561422,5.243857,0.713310,7.706210,61.535600,66.123346,22.116552,4.736067,15.922025,16.019741
min,4000.000000,0.250000,2.250000,0.000000,7.800000,0.275000,0.000000,0.000000,0.000000,0.000000,...,28.500000,17.250000,0.000000,0.000000,28.900000,6.611111,0.000000,75.900000,-11.400000,6.560000
25%,10000.000000,3.333333,8.666667,1.200000,23.225000,3.400000,2.200000,5.100000,1.750000,86.842105,...,50.181818,32.181818,0.000000,0.812500,142.567568,84.172414,0.461538,82.900000,11.100000,26.860000
50%,28000.000000,6.250000,11.000000,2.375000,30.825000,5.525000,4.975000,9.233333,3.550000,94.000000,...,53.944444,35.769231,0.000000,2.405405,189.636364,107.833333,3.277778,86.400000,18.800000,41.100000
75%,92000.000000,9.500000,14.000000,4.925000,37.825000,8.525000,10.125000,15.375000,5.900000,97.517730,...,57.687500,38.000000,0.090909,5.863636,217.892857,145.722222,16.166667,90.600000,29.400000,49.990000
max,550000.000000,30.500000,24.250000,23.766667,82.525000,28.475000,37.866667,87.275000,25.000000,100.000000,...,93.698113,49.425926,6.475000,42.000000,298.200000,308.739130,114.384615,99.400000,85.969144,68.840000

In [9]:
dataset_a.columns

Index(['year', 'state', 'colonies_inventory', 'days_with_aqi', 'good_days',
       'moderate_days', 'unhealthy_for_sensitive_groups_days',
       'unhealthy_days', 'very_unhealthy_days', 'hazardous_days', 'max_aqi',
       '90th_percentile_aqi', 'median_aqi', 'days_co', 'days_no2',
       'days_ozone', 'days_pm2.5', 'days_pm10', 'temperature_max',
       'temperature_min', 'precipitation_total'],
      dtype='object')

In [10]:
dataset_b.columns

Index(['year', 'state', 'colonies_inventory', 'colonies_renovated_pct',
       'colonies_loss_deadout_pct', 'colonies_disease_pct',
       'colonies_varroa_mites_pct', 'colonies_other_causes_pct',
       'colonies_pesticides_pct', 'colonies_other_pests_pct',
       'colonies_unknown_causes_pct', 'pct_beekeepers_exclusive_state',
       'pct_colonies_exclusive_state', 'total_loss_weighted_avg',
       'days_with_aqi', 'good_days', 'moderate_days',
       'unhealthy_for_sensitive_groups_days', 'unhealthy_days',
       'very_unhealthy_days', 'hazardous_days', 'max_aqi',
       '90th_percentile_aqi', 'median_aqi', 'days_co', 'days_no2',
       'days_ozone', 'days_pm2.5', 'days_pm10', 'temperature_max',
       'temperature_min', 'precipitation_total'],
      dtype='object')