In [1]:
#!/usr/bin/env python

"""main.ipynb:Main python notebook to run analysis and models for the bee project.
"""
__author__      = "Vincent Amedekah, Nathan Smooha, Elizabeth Gutierrez-Zaheer "
__copyright__   = "Copyright 2022, Bee Project"

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import datetime64
import get_data as data

dataset_a, dataset_b,dataset_a_test,dataset_b_test,weather_data, bee_data, bee_full_data, air_data = data.get_data()

In [2]:
dataset_b.head()

,year,state,colonies_inventory,colonies_renovated_pct,colonies_loss_deadout_pct,colonies_disease_pct,colonies_varroa_mites_pct,colonies_other_causes_pct,colonies_pesticides_pct,colonies_other_pests_pct,...,90th_percentile_aqi,median_aqi,days_co,days_no2,days_ozone,days_pm2.5,days_pm10,temperature_max,temperature_min,precipitation_total
234,2015-01-01,alabama,7000,4.25,15.50,0.050,23.225,4.325,1.825,31.225,...,56.222222,39.333333,0.000000,0.666667,137.666667,145.722222,3.222222,91.9,30.0,61.36
235,2015-01-01,arizona,26000,26.75,19.00,1.775,34.725,9.525,10.225,19.775,...,66.230769,40.461538,0.000000,3.384615,207.615385,45.153846,103.076923,94.2,28.1,14.39
236,2015-01-01,arkansas,24000,10.75,16.00,2.375,47.700,9.675,9.800,29.225,...,54.454545,35.090909,0.000000,2.636364,157.727273,87.909091,0.000000,91.6,26.1,67.31
237,2015-01-01,california,275000,13.00,11.75,7.375,38.200,11.550,15.450,15.450,...,84.537037,49.425926,0.074074,5.592593,213.555556,111.018519,13.962963,91.0,32.8,15.04
238,2015-01-01,colorado,29000,5.00,11.25,7.575,37.825,4.525,9.900,7.150,...,54.774194,35.451613,0.096774,9.354839,202.193548,19.612903,58.709677,81.8,14.2,21.73

In [3]:
dataset_b['state'].unique()

array(['alabama', 'arizona', 'arkansas', 'california', 'colorado',
       'florida', 'georgia', 'hawaii', 'idaho', 'illinois', 'indiana',
       'iowa', 'kansas', 'kentucky', 'louisiana', 'maine', 'michigan',
       'minnesota', 'mississippi', 'missouri', 'montana', 'nebraska',
       'new jersey', 'new york', 'north carolina', 'north dakota', 'ohio',
       'oregon', 'pennsylvania', 'south dakota', 'tennessee', 'texas',
       'utah', 'vermont', 'virginia', 'washington', 'west virginia',
       'wisconsin', 'wyoming'], dtype=object)

In [4]:
dataset_b.describe()

,colonies_inventory,colonies_renovated_pct,colonies_loss_deadout_pct,colonies_disease_pct,colonies_varroa_mites_pct,colonies_other_causes_pct,colonies_pesticides_pct,colonies_other_pests_pct,colonies_unknown_causes_pct,pct_beekeepers_exclusive_state,...,90th_percentile_aqi,median_aqi,days_co,days_no2,days_ozone,days_pm2.5,days_pm10,temperature_max,temperature_min,precipitation_total
count,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,...,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000
mean,68967.032967,7.261294,11.363553,3.490354,31.415629,6.217277,6.801435,11.888858,4.317582,87.738751,...,54.818950,34.979716,0.170188,5.203739,175.705873,123.012133,13.724926,86.683092,21.073568,39.390526
std,100305.722069,5.217433,4.163648,3.349669,12.027392,3.834975,6.024167,10.755110,3.499764,18.048177,...,8.561422,5.243857,0.713310,7.706210,61.535600,66.123346,22.116552,4.736067,15.922025,16.019741
min,4000.000000,0.250000,2.250000,0.000000,7.800000,0.275000,0.000000,0.000000,0.000000,0.000000,...,28.500000,17.250000,0.000000,0.000000,28.900000,6.611111,0.000000,75.900000,-11.400000,6.560000
25%,10000.000000,3.333333,8.666667,1.200000,23.225000,3.400000,2.200000,5.100000,1.750000,86.842105,...,50.181818,32.181818,0.000000,0.812500,142.567568,84.172414,0.461538,82.900000,11.100000,26.860000
50%,28000.000000,6.250000,11.000000,2.375000,30.825000,5.525000,4.975000,9.233333,3.550000,94.000000,...,53.944444,35.769231,0.000000,2.405405,189.636364,107.833333,3.277778,86.400000,18.800000,41.100000
75%,92000.000000,9.500000,14.000000,4.925000,37.825000,8.525000,10.125000,15.375000,5.900000,97.517730,...,57.687500,38.000000,0.090909,5.863636,217.892857,145.722222,16.166667,90.600000,29.400000,49.990000
max,550000.000000,30.500000,24.250000,23.766667,82.525000,28.475000,37.866667,87.275000,25.000000,100.000000,...,93.698113,49.425926,6.475000,42.000000,298.200000,308.739130,114.384615,99.400000,85.969144,68.840000

In [5]:
dataset_b.columns

Index(['year', 'state', 'colonies_inventory', 'colonies_renovated_pct',
       'colonies_loss_deadout_pct', 'colonies_disease_pct',
       'colonies_varroa_mites_pct', 'colonies_other_causes_pct',
       'colonies_pesticides_pct', 'colonies_other_pests_pct',
       'colonies_unknown_causes_pct', 'pct_beekeepers_exclusive_state',
       'pct_colonies_exclusive_state', 'total_loss_weighted_avg',
       'days_with_aqi', 'good_days', 'moderate_days',
       'unhealthy_for_sensitive_groups_days', 'unhealthy_days',
       'very_unhealthy_days', 'hazardous_days', 'max_aqi',
       '90th_percentile_aqi', 'median_aqi', 'days_co', 'days_no2',
       'days_ozone', 'days_pm2.5', 'days_pm10', 'temperature_max',
       'temperature_min', 'precipitation_total'],
      dtype='object')

# Preprocessing and EDA

In [6]:
import scipy.stats as st
import pylab as py

from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KernelDensity

from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import GridSearchCV, LeaveOneOut

import statsmodels.api as sm
import statsmodels.graphics.tsaplots as tsap
from statsmodels.compat import lzip
from statsmodels.stats.diagnostic import het_white

from linearmodels import PooledOLS

from sklearn.linear_model import ElasticNet
from sklearn.ensemble import RandomForestRegressor

from merf.merf import MERF

from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
# Remove unnecessary columns and columns that cause the matrix of exogenous variables to not be full rank
#df_b = dataset_b.drop(labels=['days_with_aqi','good_days','moderate_days','unhealthy_for_sensitive_groups_days','max_aqi','90th_percentile_aqi','median_aqi'], axis=1)
df_b = dataset_b[['year', 'state', 'colonies_inventory', 'colonies_renovated_pct','colonies_loss_deadout_pct', 'colonies_disease_pct','colonies_varroa_mites_pct', 'colonies_other_causes_pct','colonies_pesticides_pct', 'colonies_other_pests_pct','colonies_unknown_causes_pct', 'pct_beekeepers_exclusive_state','pct_colonies_exclusive_state', 'total_loss_weighted_avg','unhealthy_days', 'very_unhealthy_days', 'hazardous_days', 'days_no2', 'days_ozone', 'days_pm2.5']].copy()

In [ ]:
# Rearrange the columns so the dataframe is organized by units first then time
# This is to match the data setup described above
df_b = df_b[[df_b.columns[1]] + [df_b.columns[0]] + list(df_b.columns[2:])]

In [ ]:
# Sort the data by state-year in ascending order
df_b.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)
# Reset Index
df_b.reset_index(drop=True, inplace=True)

**Histogram of Dependent Variable**

In [ ]:
colonies_inventory = df_b['colonies_inventory'].values
plt.figure(figsize=(15, 10))
n, bins, patches = plt.hist(x=colonies_inventory, bins='auto', density=True, histtype='bar', align='mid', orientation='vertical', rwidth=0.85)
plt.grid(axis='y', alpha=0.75)
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()

In [ ]:
# for state in df_b['state'].unique():
#     df_temp = df_b[df_b['state']==state].copy()
#     colonies_inventory = df_temp['colonies_inventory'].values
#     n, bins, patches = plt.hist(x=colonies_inventory, bins='auto', density=True, histtype='bar', align='mid', orientation='vertical', rwidth=0.85)
#     plt.grid(axis='y', alpha=0.75)
#     plt.xlabel('Value')
#     plt.ylabel('Frequency')
#     plt.show()

**Box-Cox Transformation**

In [ ]:
# transform training data & save lambda value
fitted_data, fitted_lambda = st.boxcox(colonies_inventory)

# creating axes to draw plots
fig, ax = plt.subplots(1, 2)

# plotting the original data(non-normal) and
# fitted data (normal)
sns.distplot(colonies_inventory, hist = False, kde = True,
            kde_kws = {'shade': True, 'linewidth': 2},
            label = "Non-Normal", color ="blue", ax = ax[0])

sns.distplot(fitted_data, hist = False, kde = True,
            kde_kws = {'shade': True, 'linewidth': 2},
            label = "Normal", color ="green", ax = ax[1])
 
# adding legends to the subplots
#plt.legend(loc = "upper right")
 
# rescaling the subplots
fig.set_figheight(10)
fig.set_figwidth(15)
 
print(f"Lambda value used for Transformation: {fitted_lambda}")

In [ ]:
fig, ax = plt.subplots(figsize=(15, 10))
sm.qqplot(fitted_data, line ='45', ax=ax)
plt.show()

**Examine Trends in the Dependent Variable**

In [ ]:
for state in df_b['state'].unique():
    print(state)
    df_temp = df_b[df_b['state']==state].copy()
    plt.plot(df_temp['year'], df_temp['colonies_inventory'])
    plt.show()
    print('\n')

**Examine Relationship Between Independent Variables and Dependent Variable**

In [ ]:
for col in df_b.columns[3:]:
    print(col)
    sns.scatterplot(x=df_b[col], y=df_b['colonies_inventory'])#, hue=df_b['state'])
    plt.show()
    print('\n')

# Pooled OLS Regression Model

In this panel dataset, we have collected data for 38 US states, or "units", over a period of time from 2015 to 2021. This dataset is a "fixed and balanced panel" since each state is tracked over the same number of time periods, and the same set of states are tracked in each time period.

For each unit, we have included 29 explanatory variables, which all change across time periods. We wish to study the impact of these measured variables on the response variable, which is the total number of bee colonies in a state. Thus, we have a three-dimensional dataset in which each row represents a unique unit, each column contains the data from one of the explanatory variables for that unit, and the "z-axis" contains the sequence of time perios over which the unit has been tracked.

Our goal is to choose and fit a regression model that is suitable for this panel dataset. Our regression model should allow us to express yearly bee colony numbers experienced by state $i$ at time period (i.e., year) $t$ as some function $f(\cdot)$ of the explanatory variables in state $i$ during time period $t$. This can be written in the following form

$$y_{t}^{i}=f(x_{t}^{i})+\epsilon_{t}^{i}$$

where $x_{t}^{i}$ is our $(n+1) \times 1$ feature vector (i.e., $n=29$ plus 1 constant), and $\epsilon^{i}_{t}$ is the residual error of regression with a certain mean and variance, and it captures the variance that the model isn't able to "explain." 

With the Pooled OLS regresion model, the equation above can be rewritten as a linear equation. For observational units $i = 1, \ldots, m=39$, we have

$$\mathbf{y}^i = \mathbf{X}^i\beta + \mathbf{\epsilon}^i$$

where $\mathbf{y}^i$ is a $T \times 1$ vector of response variables, $\mathbf{\epsilon}^{i}$ is a $T \times 1$ vector of error terms, $\mathbf{X}^i$ is a $T \times (n+1)$ matrix written as 

$$\mathbf{X}^{i}=\left[\begin{array}{c}
(x_{1}^{i})^{\text{T}}\\
(x_{2}^{i})^{\text{T}}\\
\vdots\\
(x_{T}^{i})^{\text{T}}
\end{array}\right]$$

and $\beta$ is the $(n+1) \times 1$ population parameter we want to estimate. So, we have the same $\beta$ for all $t = 1,\ldots,T=7$. The objective of training the model on the panel data dataset is to find the fitted vector of coefficients $\hat{\beta}$, and the pooled OLS estimator is given by

$$\begin{array}{lcl}
\hat{\beta} & = & \left({\displaystyle \sum_{i=1}^{m}}\left[\mathbf{X}^{i}\right]^{\text{T}}\mathbf{X}^{i}\right)^{-1}\left({\displaystyle \sum_{i=1}^{m}}\left[\mathbf{X}^{i}\right]^{\text{T}}\mathbf{y}^{i}\right)\\
 & = & \left({\displaystyle \sum_{i=1}^{m}}{\displaystyle \sum_{t=1}^{T}}\left[x_{t}^{i}\right]^{\text{T}}x_{t}^{i}\right)^{-1}\left({\displaystyle \sum_{i=1}^{m}}{\displaystyle \sum_{t=1}^{T}}\left[x_{t}^{i}\right]^{\text{T}}y_{t}^{i}\right)
\end{array}$$

The pooled OLS regression model is often a good starting point and reference for other models related to panel data, such as the "Fixed Effects Regression Model" or the "Random Effects Regression Model."

In [ ]:
rmse = []
mae = []
mape = []

for t in ['2017-01-01','2018-01-01','2019-01-01','2020-01-01','2021-01-01']:
    # Split the datasets into training and test sets
    df_train = df_b[df_b['year'] < t].copy()
    df_train.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)
    df_train.set_index(['state','year'], inplace=True)
    
    df_test = df_b[df_b['year']==t].copy()
    df_test.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)
    df_test.set_index(['state','year'], inplace=True)
    
    # X matrix from the panel data
    # Add a placeholder for the regression intercept
    exog = sm.tools.tools.add_constant(df_train[df_train.columns[1:]])
    # y vector from the panel data
    endog = df_train['colonies_inventory']
    # Build the Pooled OLS regression model
    pols_mod = PooledOLS(endog, exog)
    # Train the model on the (y,X) datasets and retrieve the training results
    pols_results = pols_mod.fit(cov_type='clustered', cluster_entity=True)
    
    # Using the exogenous variables in the testing dataset, make predictions for all 38 states for the following year
    exog = sm.tools.tools.add_constant(df_test[df_test.columns[1:]])
    y_pred = pols_results.predict(exog)
    
    # Combine the true values with the predicted values
    y_true = df_test[['colonies_inventory']]
    df_y = y_true.merge(y_pred, how='inner', left_index=True, right_index=True)
    
    # Calculate the performance metrics
    rmse.appen(mean_squared_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy(), squared=False))
    mae.append(mean_absolute_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy()))
    mape.append(mean_absolute_percentage_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy()))

In [ ]:
print('The mean RMSE value is ' + str(round(np.mean(rmse),2)))
print('The mean MAE value is ' + str(round(np.mean(mae),2)))
print('The mean MAPE value is ' + str(round(np.mean(mape),2)))

In [ ]:
# Standardizing the features
#temp = df_b[df_b.columns[3:]]
#X = StandardScaler().fit_transform(np.array(temp))

# Create a new dataframe with the adjusted features
#temp = pd.DataFrame(X, columns=df_b.columns[3:])
#df_b = pd.concat([dataset_b[['state','year','colonies_inventory']],temp], axis=1)

In [ ]:
# Set the index
df_b_temp = df_b.set_index(['state','year'])
#years = df_b.year.get_level_values('year').to_list()
#df_b['year'] = pd.Categorical(years)

In [ ]:
# X matrix from the panel data
# Add a placeholder for the regression intercept
exog = sm.tools.tools.add_constant(df_b_temp[df_b_temp.columns[1:]])
# y vector from the panel data
endog = df_b_temp['colonies_inventory']
# Build the Pooled OLS regression model
pols_mod = PooledOLS(endog, exog)
# Train the model on the (y,X) datasets and retrieve the training results
pols_results = pols_mod.fit(cov_type='clustered', cluster_entity=True)

# Store values for chicking homoskedasticity graphically
pols_fit_vals = pols_results.predict().fitted_values
pols_resids = pols_results.resids

In [ ]:
# Examine the accuracy results on the entire training dataset

# Using the exogenous variables in the testing dataset, make predictions for all 38 states for every year in the training dataset
y_pred = pols_results.predict(exog)
# Combine the true values with the predicted values
y_true = df_b_temp[['colonies_inventory']]
df_y = y_true.merge(y_pred, how='inner', left_index=True, right_index=True)

In [ ]:
# Calculate RMSE
mean_squared_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy(), squared=False)

In [ ]:
# Calculate MAE
mean_absolute_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy())

In [ ]:
# Calcualte MAPE
mean_absolute_percentage_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy())

In [ ]:
# Print the training summary
print(pols_results)

In [ ]:
pooled_y = df_b['colonies_inventory']

In [ ]:
pooled_X = sm.tools.tools.add_constant(df_b_temp[df_b_temp.columns[1:]])

In [ ]:
pooled_olsr_model = sm.OLS(endog=pooled_y, exog=pooled_X)

In [ ]:
pooled_olsr_model_results = pooled_olsr_model.fit()

In [ ]:
print(pooled_olsr_model_results.summary())

# Elastic Net

In [ ]:
rmse = {}
for a in list(np.linspace(start=1, stop=1000, num=1000, endpoint=True)):
    for l1 in list(np.linspace(start=0.1, stop=1, num=1000, endpoint=True)):
        rmse[str(a)+'-'+str(l1)] = []
        for t in ['2017-01-01','2018-01-01','2019-01-01','2020-01-01','2021-01-01']:
            # Split the datasets into training and test sets
            df_train = df_b[df_b['year'] < t].copy()
            df_train.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)
            df_train.set_index(['state','year'], inplace=True)
    
            df_test = df_b[df_b['year']==t].copy()
            df_test.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)
            df_test.set_index(['state','year'], inplace=True)
            
            # Fit the Elastic Net Regression
            y = df_train['colonies_inventory'].to_numpy()
            X = df_train[df_train.columns[1:]].to_numpy()
            elasnet_reg = ElasticNet(alpha=a, l1_ratio=l1, fit_intercept=True, max_iter=10000 , tol=1e-4, warm_start=True, positive=False, selection='cyclic')
            elastnet_reg = elasnet_reg.fit(X,y)
    
            # Using the exogenous variables in the testing dataset, make predictions for all 38 states for the following year
            X_test = df_test[df_test.columns[1:]].to_numpy()
            y_pred = elasnet_reg.predict(X_test)
            
            # Put the true values and the predicted values into the same dataframe for comparison
            df_y = df_test[['colonies_inventory']].copy()
            df_y['predictions'] = y_pred
    
            # Calculate the performance metric
            rmse[str(a)+'-'+str(l1)].append(mean_squared_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy(), squared=False))

In [ ]:
test = pd.DataFrame.from_dict(rmse, orient='index')

In [ ]:
test['average'] = test.mean(axis=1)

In [ ]:
test.iloc[test['average'].argmin()].name

# Fixed Effects Regression Model

Errors may be introduced to the model by the omission of variables that are not measurable. These variables represent qualities that are intrinsic to the unit being measured. For our panel dataset where a unit is a state, an example of unit-specific variables could be the yearly decisions being made related to honey bee preservation in a particular state. These factors impact the inventory of honey bee colonies each year, but they are unable to be direclty measured. Yet, the omission of such factors from the regression matrix $\mathbf{X}$ could lead to an improperly defined model.

Thus, we will adjust the linear regression model for state $i$ as follows

# Mixed Effects Random Forest

In [ ]:
corr = df_b.drop(['state','year'], axis=1).corr()
plt.figure(figsize=(15, 12))

sns.heatmap(corr[(corr >= 0.2) | (corr <= -0.2)], 
            cmap='viridis', vmax=1.0, vmin=-1.0, linewidths=0.1,
            annot=True, annot_kws={"size": 8}, square=True);

In [ ]:
#df_train = df_b.drop(labels=['unhealthy_days', 'very_unhealthy_days', 'hazardous_days', 'days_no2', 'days_ozone', 'days_pm2.5'], axis=1)
#df_train = df_b.copy()
df_train = df_b[df_b['year'] < '2017-01-01'].copy()
df_train.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)

df_test = df_b.copy()
df_test.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)

y_train = df_train['colonies_inventory']
clusters_train = df_train['state']
X_train = df_train.drop(['state','colonies_inventory'], axis=1)
X_train.set_index(['year'], inplace=True)
Z_train = np.ones(shape=(X_train.shape[0],1))
Z_train = np.concatenate((Z_train, X_train[list(X_train.columns)].to_numpy()), axis=1)

In [ ]:
rfr = RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='squared_error', max_depth=None, max_features='sqrt', 
                                                  max_leaf_nodes=None, max_samples=None, min_impurity_decrease=0.0, min_samples_leaf=1, 
                                                  min_samples_split=2, min_weight_fraction_leaf=0.0, n_estimators=10000, 
                                                  n_jobs=-1, oob_score=False, random_state=None, verbose=0, warm_start=False)

In [ ]:
rfr.fit(X_train, y_train)

In [ ]:
def plot_feature_importance(importance,names,model_type):

    #Create arrays from feature importance and feature names
    feature_importance = np.array(importance)
    feature_names = np.array(names)

    #Create a DataFrame using a Dictionary
    data={'feature_names':feature_names,'feature_importance':feature_importance}
    fi_df = pd.DataFrame(data)

    #Sort the DataFrame in order decreasing feature importance
    fi_df.sort_values(by=['feature_importance'], ascending=False,inplace=True)

    #Define size of bar plot
    plt.figure(figsize=(10,8))
    #Plot Searborn bar chart
    sns.barplot(x=fi_df['feature_importance'], y=fi_df['feature_names'])
    #Add chart labels
    plt.title(model_type + ' FEATURE IMPORTANCE')
    plt.xlabel('FEATURE IMPORTANCE')
    plt.ylabel('FEATURE NAMES')

In [ ]:
plot_feature_importance(rfr.feature_importances_,df_train.columns[3:],'RANDOM FOREST')

In [ ]:
df_b_upd = df_b[['year','state','colonies_inventory','pct_beekeepers_exclusive_state','pct_colonies_exclusive_state','days_ozone','unhealthy_days',
                 'colonies_pesticides_pct','colonies_disease_pct','days_pm2.5','colonies_loss_deadout_pct']].copy()

In [ ]:
rmse = {}
#mae = {}
#mape = {}

for trees in list(range(100,1050,100)):
    rmse[trees] = []
    for i,t in enumerate(['2017-01-01','2018-01-01','2019-01-01','2020-01-01','2021-01-01'], start=1):
        # Split the datasets into training and test sets
        df_train = df_b_upd[df_b_upd['year'] < t].copy()
        df_train.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)

        df_test = df_b_upd[df_b_upd['year']==t].copy()
        df_test.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)

        # Fit the Mixed Effects Random Forest Regression
        y_train = df_train['colonies_inventory']
        clusters_train = df_train['state']
        X_train = df_train.drop(['state','colonies_inventory'], axis=1)
        X_train.set_index(['year'], inplace=True)
        Z_train = np.ones(shape=(X_train.shape[0],1))
        Z_train = np.concatenate((Z_train, X_train[list(X_train.columns)].to_numpy()), axis=1)
        merf = MERF(fixed_effects_model=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='squared_error', max_depth=None, max_features='sqrt', 
                                                          max_leaf_nodes=None, max_samples=None, min_impurity_decrease=0.0, min_samples_leaf=1, 
                                                          min_samples_split=2, min_weight_fraction_leaf=0.0, n_estimators=trees, 
                                                          n_jobs=-1, oob_score=False, random_state=None, verbose=0, warm_start=False), 
                gll_early_stop_threshold=1e-4, max_iterations=100)
        merf.fit(X_train, Z_train, clusters_train, y_train)

        # Using the exogenous variables in the testing dataset, make predictions for all 39 states for the following year
        clusters_test = df_test['state']
        X_test = df_test.drop(['state','colonies_inventory'], axis=1)
        X_test.set_index(['year'], inplace=True)
        Z_test = np.ones(shape=(X_test.shape[0],1))
        Z_test = np.concatenate((Z_test, X_test[list(X_test.columns)].to_numpy()), axis=1)
        y_pred = merf.predict(X_test, Z_test, clusters_test)

        # Put the true values and the predicted values into the same dataframe for comparison
        df_y = df_test[['colonies_inventory']].copy()
        df_y['predictions'] = y_pred

        # Calculate the performance metric
        rmse[trees].append(mean_squared_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy(), squared=False))
        
        #rmse.append(mean_squared_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy(), squared=False))
        #mae.append(mean_absolute_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy()))
        #mape.append(mean_absolute_percentage_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy()))

In [ ]:
test = pd.DataFrame.from_dict(rmse, orient='columns')

In [ ]:
cv_results = test.to_numpy()

In [ ]:
cv_results = np.transpose(cv_results)

In [ ]:
cv_avgs = np.mean(cv_results, axis=1)

In [ ]:
test.mean()

In [ ]:
# Plot the varying values for lambda on the x-axis, and the average MSE
fig = plt.figure()
plt.figure(figsize = (10, 10))
plt.plot(rmse.keys(), cv_results, '--')
plt.plot(rmse.keys(), cv_avgs, linewidth=3, color='black', label='Average across the folds')
plt.vlines(x=600, ymin=np.min(cv_results)-500, ymax=np.max(cv_results), colors='black', linestyles='dashed', label='Optimal Number of Trees = ' + str(600))
plt.title('RMSE of Each Fold')
plt.xlabel('Number of Trees')
plt.ylabel('Root Mean Square Error')
plt.legend(loc='lower right')
plt.show()

--------------

In [ ]:
rmse = []
mae = []
mape = []
df_results = []

for i,t in enumerate(['2017-01-01','2018-01-01','2019-01-01','2020-01-01','2021-01-01'], start=1):
    # Split the datasets into training and test sets
    df_train = df_b[df_b['year'] < t].copy()
    df_train.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)

    df_test = df_b[df_b['year']==t].copy()
    df_test.sort_values(by=['state','year'], axis=0, ascending=True, inplace=True)

    # Fit the Mixed Effects Random Forest Regression
    y_train = df_train['colonies_inventory']
    clusters_train = df_train['state']
    X_train = df_train.drop(['state','colonies_inventory'], axis=1)
    X_train.set_index(['year'], inplace=True)
    Z_train = np.ones(shape=(X_train.shape[0],1))
    Z_train = np.concatenate((Z_train, X_train[list(X_train.columns)].to_numpy()), axis=1)
    merf = MERF(fixed_effects_model=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='squared_error', max_depth=None, max_features='sqrt', 
                                                      max_leaf_nodes=None, max_samples=None, min_impurity_decrease=0.0, min_samples_leaf=1, 
                                                      min_samples_split=2, min_weight_fraction_leaf=0.0, n_estimators=600, 
                                                      n_jobs=-1, oob_score=False, random_state=None, verbose=0, warm_start=False), 
            gll_early_stop_threshold=1e-4, max_iterations=100)
    merf.fit(X_train, Z_train, clusters_train, y_train)

    # Using the exogenous variables in the testing dataset, make predictions for all 38 states for the following year
    clusters_test = df_test['state']
    X_test = df_test.drop(['state','colonies_inventory'], axis=1)
    X_test.set_index(['year'], inplace=True)
    Z_test = np.ones(shape=(X_test.shape[0],1))
    Z_test = np.concatenate((Z_test, X_test[list(X_test.columns)].to_numpy()), axis=1)
    y_pred = merf.predict(X_test, Z_test, clusters_test)
    
    # Put the true values and the predicted values into the same dataframe for comparison
    df_y = df_test[['colonies_inventory']].copy()
    df_y['predictions'] = y_pred

    # Calculate the performance metric
    rmse.append(mean_squared_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy(), squared=False))
    mae.append(mean_absolute_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy()))
    mape.append(mean_absolute_percentage_error(df_y['colonies_inventory'].to_numpy(), df_y['predictions'].to_numpy()))
    df_results.append(df_y)

In [ ]:
rmse

In [ ]:
mae

In [ ]:
mape

In [ ]:
print('The mean RMSE value is ' + str(round(np.mean(rmse),4)))
print('The mean MAE value is ' + str(round(np.mean(mae),4)))
print('The mean MAPE value is ' + str(round(np.mean(mape),4)))

In [ ]:
df_2017 = df_results[0]

In [ ]:
df_2017['year'] = '2017-01-01'

In [ ]:
df_2018 = df_results[1]

In [ ]:
df_2018['year'] = '2018-01-01'

In [ ]:
df_2019 = df_results[2]

In [ ]:
df_2019['year'] = '2019-01-01'

In [ ]:
df_2020 = df_results[3]

In [ ]:
df_2020['year'] = '2020-01-01'

In [ ]:
df_2021 = df_results[4]

In [ ]:
df_2021['year'] = '2021-01-01'

In [ ]:
df_test = pd.concat([df_2017,df_2018,df_2019,df_2020,df_2021], axis=0)

In [ ]:
df_test = df_test.groupby('year').sum()

In [ ]:
df_test.reset_index(inplace=True)

In [ ]:
mean_squared_error(df_test[df_test['year']=='2021-01-01']['colonies_inventory'].values, df_test[df_test['year']=='2021-01-01']['predictions'].values, squared=False)

In [ ]:
mean_absolute_error(df_test[df_test['year']=='2021-01-01']['colonies_inventory'].values, df_test[df_test['year']=='2021-01-01']['predictions'].values)

In [ ]:
mean_absolute_percentage_error(df_test[df_test['year']=='2021-01-01']['colonies_inventory'].values, df_test[df_test['year']=='2021-01-01']['predictions'].values)

In [ ]:
results_list = [0.0507,0.0569,0.0148,0.0351,0.0154]

In [ ]:
np.mean(results_list)

In [10]:
mean_squared_error(np.array([72673.076923]), np.array([63348.063277]), squared=False)

9325.013646

--------------

In [ ]:
merf = MERF(fixed_effects_model=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='squared_error', max_depth=None, max_features='sqrt', 
                                                      max_leaf_nodes=None, max_samples=None, min_impurity_decrease=0.0, min_samples_leaf=1, 
                                                      min_samples_split=2, min_weight_fraction_leaf=0.0, n_estimators=1000, 
                                                      n_jobs=-1, oob_score=False, random_state=None, verbose=0, warm_start=False), 
            gll_early_stop_threshold=1e-4,, max_iterations=100)

In [ ]:
y_train = df_b['colonies_inventory']

In [ ]:
clusters_train = df_b['state']

In [ ]:
X_train = df_b.drop(['state','colonies_inventory'], axis=1)

In [ ]:
X_train.set_index(['year'], inplace=True)

In [ ]:
Z_train = np.ones(shape=(X_train.shape[0],1))
Z_train = np.concatenate((Z_train, X_train[list(X_train.columns)].to_numpy()), axis=1)

In [ ]:
merf.fit(X_train, Z_train, clusters_train, y_train)

In [ ]:
y_hat = merf.predict(X_train, Z_train, clusters_train)

In [ ]:
mean_squared_error(y_train.to_numpy(), y_hat, squared=False)